bowtie2 --rg-id NEX1_1 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_1_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_1_R2.fastq.gz -S NEX1_1.sam
bowtie2 --rg-id NEX1_2 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_2_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_2_R2.fastq.gz -S NEX1_2.sam
bowtie2 --rg-id NEX1_4 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX2_4_S1_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX2_4_S1_R2.fastq.gz -S NEX1_4.sam
bowtie2 --rg-id NEX1_5 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_5_25_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_5_25_R2.fastq.gz -S NEX1_5.sam
bowtie2 --rg-id NEX1_6 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_6_26_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_6_26_R2.fastq.gz -S NEX1_6.sam
bowtie2 --rg-id NEX1_7 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_7_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_7_R2.fastq.gz -S NEX1_7.sam
bowtie2 --rg-id NEX1_8 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_8_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_8_R2.fastq.gz -S NEX1_8.sam
bowtie2 --rg-id NEX1_9 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_9_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_9_R2.fastq.gz -S NEX1_9.sam
bowtie2 --rg-id NEX1_10 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_10_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_10_R2.fastq.gz -S NEX1_10.sam
bowtie2 --rg-id NEX1_11 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_11_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_11_R2.fastq.gz -S NEX1_11.sam
bowtie2 --rg-id NEX1_12 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_12_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_12_R2.fastq.gz -S NEX1_12.sam
bowtie2 --rg-id NEX1_13 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_13_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_13_R2.fastq.gz -S NEX1_13.sam
bowtie2 --rg-id NEX1_14 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_14_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_14_R2.fastq.gz -S NEX1_14.sam
bowtie2 --rg-id NEX1_15 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_15_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_15_R2.fastq.gz -S NEX1_15.sam
bowtie2 --rg-id NEX1_16 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_16_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_16_R2.fastq.gz -S NEX1_16.sam
bowtie2 --rg-id NEX1_17 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_17_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_17_R2.fastq.gz -S NEX1_17.sam
bowtie2 --rg-id NEX1_19 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_19_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_19_R2.fastq.gz -S NEX1_19.sam
bowtie2 --rg-id NEX1_20 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_20_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_20_R2.fastq.gz -S NEX1_20.sam
bowtie2 --rg-id NEX1_22 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX2_22_S2_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX2_22_S2_R2.fastq.gz -S NEX1_22.sam
bowtie2 --rg-id NEX1_23 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX2_23_S3_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX2_23_S3_R2.fastq.gz -S NEX1_23.sam
bowtie2 --rg-id NEX1_24 -x /work/jgjohns6/Marmoset/calJac3.ref -1 /storage/datasets/callithrix/fastq/NEX1_24_R1.fastq.gz -2 /storage/datasets/callithrix/fastq/NEX1_24_R2.fastq.gz -S NEX1_24.sam

